version: "3.9"
services:
  system-service:
    image: poezegast222/python-db-test2
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: APIdb
      POSTGRES_USER: Jurn
      POSTGRES_PASSWORD: test
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: APIdb
      POSTGRES_USER: Jurn
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data_volume:
